#!/bin/bash

#use this script to download the hg19 genome

cd ~/wgbs/reference/human/genome/hg19/

wget hgdownload.cse.ucsc.edu/goldenPath/hg19/bigZips/chromFa.tar.gz
tar -zxvf chromFa.tar.gz
cat chr*.fa > hg19.fa
rm chr*.fa
